name: Build & Deploy VHS GIF

on:
  push:
    branches:
      - main
    paths:
      - vhs.tape

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-gif:
    name: Build GIF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y cmatrix

      - name: Build tape
        uses: charmbracelet/vhs-action@v2.1.1
        with:
          path: "vhs.tape"
          version: "v0.12.1"

      - name: Upload GIF
        uses: actions/upload-artifact@v7
        with:
          path: vhs.gif
          name: vhs

  deploy-gif:
    name: Deploy GIF
    runs-on: ubuntu-latest
    needs: build-gif
    steps:
      - name: Download GIF
        uses: actions/download-artifact@v4
        with:
          name: vhs

      - name: Move tape
        run: |
          mkdir dist
          mv vhs.gif dist

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
